// Generated by Xata Codegen 0.30.1. Please do not edit.
import type { BaseClientOptions, } from "@xata.io/client";
import { buildClient } from "@xata.io/client";



export type DatabaseSchema = {};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://shakthi-s-workspace-547a4a.us-east-1.xata.sh/db/shakthi_snapcast",
     apiKey: process.env.XATA_API_KEY,
     branch: "main",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options });
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
